name: CI con Selenium

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Ejecutar test funcional
      run: |
        chmod +x ./run_test_busqueda.sh
        ./run_test_busqueda.sh
